# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20150529_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='languages',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'Javascript')], max_length=2),
        ),
    ]
