# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160225_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='languages',
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('GO', 'Golang'), ('JS', 'Javascript'), ('RB', 'Ruby'), ('HTML', 'HTML')], max_length=2, null=True),
        ),
    ]
