# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160502_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('go', 'Golang'), ('javascript', 'Javascript'), ('ruby', 'Ruby'), ('htmlmixed', 'HTML')], max_length=2, null=True),
        ),
    ]
