# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160502_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
